routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/',  url('/home'));

Route::group(['middleware' => ['auth']], function () {
    // HOME ROUTE
    Route::get('/home', 'HomeController@index')->name('home');

    //SUPPLY ROUTE
    Route::get('/supply/status', 'SupplyController@status')->name('supply.status');
    Route::post('/supply/multi-list', 'SupplyController@multiList')->name('supply.multi');

    //PROFILE ROUTES
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    //USERS ROUTES
    Route::get('/users/separators', 'UserController@getSeparators')->name('users.separators');
    Route::post('/users/{id}/toggle-status', 'UserController@toggleStatus')->name('users.toggleStatus');

    //PDF ROUTES
    Route::post('/pdf/{view}/', 'PDFController@generate')->name('pdf.generate');
    Route::post('/pdf/download/{view}', 'PDFController@download')->name('pdf.download');

    //CSV ROUTES
    Route::get('/csv/{type}/{id}/export', 'CSVController@exportRecount')->name('csv.export-recount');
    Route::post('/csv/list/export', 'CSVController@exportList')->name('csv.export-list');

    //NOTES ROUTES
    Route::get('/notes/', 'RecountController@noteIndex')->name('notes.index');
    Route::get('/notes/import', 'RecountController@import')->name('notes.import');
    Route::get('/notes/{id}/items/', 'RecountController@noteItems')->name('notes.items');
    Route::delete('/notes/{id}/destroy/', 'RecountController@noteDestroy')->name('notes.destroy');

    //FILIAL NOTES ROUTES
    Route::get('/filial-notes/', 'FilialRecountController@noteIndex')->name('filial-notes.index');
    Route::get('/filial-notes/import', 'FilialRecountController@import')->name('filial-notes.import');
    Route::get('/filial-notes/{id}/items/', 'FilialRecountController@noteItems')->name('filial-notes.items');
    Route::delete('/filial-notes/{id}/destroy/', 'FilialRecountController@noteDestroy')->name('filial-notes.destroy');

    //ENTRY REPORT ROUTES
    Route::get('/entry-reports/{type}/index', 'EntryReportController@index')->name('entry-reports.index');
    Route::post('/entry-reports/{reference_id}/{table}/store', 'EntryReportController@store')->name('entry-reports.store');
    Route::delete('/entry-reports/{id}/destroy/', 'EntryReportController@destroy')->name('entry-reports.destroy');
    Route::delete('/entry-reports/{id}/rollback/', 'EntryReportController@rollback')->name('entry-reports.rollback');

    //AUDIT ROUTES
    Route::get('/audits', 'AuditController@index')->name('audits.index');

    // CRUD ROUTES
    Route::resources([
        'supply'            => 'SupplyController' ,
        'users'      		=> 'UserController',
        'recounts'          => 'RecountController',
        'filial-recounts'   => 'FilialRecountController'
    ]);

    //QUEUES ROUTES
    Route::get('/queue/updates', 'QueueController@checkForUpdates')->name('queue.updates');

});

resources/views/layouts/navbars/sidebar.blade.php
@php use App\Entities\EntryReport; @endphp
<div class="sidebar" data-color="orange">
    <!--
      Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
  -->
    <div class="logo">
        <a href="{{ route('home') }}" class="simple-text logo-mini">
            <img src="{{ asset('assets/img/now-logo.png') }}" alt="" width="30" height="30">
        </a>
        <a href="{{ route('home') }}" class="simple-text logo-normal">
            {{ env('APP_NAME') ?? "Brazil-WMS" }}
        </a>
    </div>
    <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
            <li class="@if ($activePage == 'home') active @endif">
                <a href="{{ route('home') }}">
                    <i class="now-ui-icons design_app"></i>
                    <p>{{ __('Dashboard') }}</p>
                </a>
            </li>

            <li class="@if ($activePage == 'supply') active @endif">
                <a href="{{ route('supply.index')}}">
                    <i class="now-ui-icons shopping_basket"></i>
                    <p>{{ __('Abastecimento') }}</p>
                </a>
            </li>

            <li class="nav-item dropdown @if ($activePage == 'recounts') active @endif">
                <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                    <p>{{ __('Conferências') }}</p>
                </a>
                <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item"><b>Fornecedor</b></a>
                    <a class="dropdown-item" href="{{ route('notes.index') }}">Notas de Entrada</a>
                    <a class="dropdown-item" href="{{ route('recounts.index') }}">Controle de Conferências</a>
                    <hr>
                    <a class="dropdown-item"><b>Entre Filiais</b></a>
                    <a class="dropdown-item" href="{{ route('filial-notes.index') }}">Notas de Entrada</a>
                    <a class="dropdown-item" href="{{ route('filial-recounts.index') }}">Controle de Conferências</a>
                </div>
            </li>

            <li class="nav-item dropdown @if ($activePage == 'entry_report') active @endif">
                <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    <i class="now-ui-icons shopping_box"></i>
                    <p>{{ __('Relatórios de Entrada') }}</p>
                </a>
                <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item"><b>Tipos de relatórios</b></a>
                    <a class="dropdown-item"
                       href="{{ route('entry-reports.index', ['type' => EntryReport::TYPE_ESTOQUE]) }}">Separação de
                        estoque</a>
                    <a class="dropdown-item"
                       href="{{ route('entry-reports.index', ['type' => EntryReport::TYPE_LOJA]) }}">Recebimento
                        em loja</a>
                </div>
            </li>

            <li class="@if ($activePage == 'audits') active @endif">
                <a href="{{ route('audits.index')}}">
                    <i class="now-ui-icons business_badge"></i>
                    <p>{{ __('Auditoria') }}</p>
                </a>
            </li>

            @if(auth()->user()->isAdmin() ?? false)
                <li class="@if ($activePage == 'users') active @endif">
                    <a href="{{ route('users.index') }}">
                        <i class="now-ui-icons users_circle-08"></i>
                        <p>{{ __('Usuários') }}</p>
                    </a>
                </li>
            @endif
        </ul>
    </div>
</div>