routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/',  url('/home'));

Route::group(['middleware' => ['auth']], function () {
    // HOME ROUTE
    Route::get('/home', 'HomeController@index')->name('home');

    //SUPPLY ROUTE
    Route::get('/supply/status', 'SupplyController@status')->name('supply.status');
    Route::post('/supply/multi-list', 'SupplyController@multiList')->name('supply.multi');

    //PROFILE ROUTES
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    //USERS ROUTES
    Route::get('/users/separators', 'UserController@getSeparators')->name('users.separators');
    Route::post('/users/{id}/toggle-status', 'UserController@toggleStatus')->name('users.toggleStatus');

    //PDF ROUTES
    Route::post('/pdf/{view}/', 'PDFController@generate')->name('pdf.generate');
    Route::post('/pdf/download/{view}', 'PDFController@download')->name('pdf.download');

    //CSV ROUTES
    Route::get('/csv/{type}/{id}/export', 'CSVController@exportRecount')->name('csv.export-recount');
    Route::post('/csv/list/export', 'CSVController@exportList')->name('csv.export-list');

    //NOTES ROUTES
    Route::get('/notes/', 'RecountController@noteIndex')->name('notes.index');
    Route::get('/notes/import', 'RecountController@import')->name('notes.import');
    Route::get('/notes/{id}/items/', 'RecountController@noteItems')->name('notes.items');
    Route::delete('/notes/{id}/destroy/', 'RecountController@noteDestroy')->name('notes.destroy');

    //FILIAL NOTES ROUTES
    Route::get('/filial-notes/', 'FilialRecountController@noteIndex')->name('filial-notes.index');
    Route::get('/filial-notes/import', 'FilialRecountController@import')->name('filial-notes.import');
    Route::get('/filial-notes/{id}/items/', 'FilialRecountController@noteItems')->name('filial-notes.items');
    Route::delete('/filial-notes/{id}/destroy/', 'FilialRecountController@noteDestroy')->name('filial-notes.destroy');

    //ENTRY REPORT ROUTES
    Route::get('/entry-reports/{type}/index', 'EntryReportController@index')->name('entry-reports.index');
    Route::post('/entry-reports/{reference_id}/{table}/store', 'EntryReportController@store')->name('entry-reports.store');
    Route::delete('/entry-reports/{id}/destroy/', 'EntryReportController@destroy')->name('entry-reports.destroy');
    Route::delete('/entry-reports/{id}/rollback/', 'EntryReportController@rollback')->name('entry-reports.rollback');

    //AUDIT ROUTES
    Route::get('/audits', 'AuditController@index')->name('audits.index');

    // CRUD ROUTES
    Route::resources([
        'supply'            => 'SupplyController' ,
        'users'      		=> 'UserController',
        'recounts'          => 'RecountController',
        'filial-recounts'   => 'FilialRecountController'
    ]);

    //QUEUES ROUTES
    Route::get('/queue/updates', 'QueueController@checkForUpdates')->name('queue.updates');

});

app/Http/Controllers/Api/FilialRecountController.php
<?php


namespace App\Http\Controllers\Api;


use App\Entities\Filial\FilialBlindNote;
use App\Entities\Filial\FilialNote;
use App\Entities\Filial\FilialRecount;
use App\Entities\Filial\FilialRecountItems;
use App\Events\AtualizaNotaCegaEvent;
use App\Http\Controllers\Controller;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpFoundation\Response;

class FilialRecountController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth.api.custom');
    }

    public function index(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                'status' => 'nullable|int|min:1|max:3',
                'search' => 'nullable|string',
            ]);

            $user = auth()->guard('api')->user();
            $status = $validated['status'] ?? null;
            $search = $validated['search'] ?? null;

            // Query principal com filtros aplicados
            $queryNotas = FilialNote::with(['recount'])
                ->withCount('items')
                ->where(function ($query) use ($status) {
                    if ($status == FilialRecount::STATUS_PENDING) {
                        $query->whereNull('recount_id')
                            ->orWhereHas('recount', function ($query) {
                                $query->where('status', FilialRecount::STATUS_PENDING);
                            });
                    } else if ($status) {
                        $query->whereHas('recount', function ($query) use ($status) {
                            $query->where('status', $status);
                        });
                    }
                });

            if ($search) {
                $queryNotas->where(function ($query) use ($search) {
                    $query->whereLike(['name_provider'], $search)
                        ->orWhereIn('nfe', explode(',', $search)); // Supondo que 'nfe' são números separados por vírgula
                });
            }

            //Execução da query
            $notes = $queryNotas
                ->where('company_id', $user->company_id)
                ->orderBy('id', 'desc')
                ->take(100)
                ->get();

            // Escondendo dados desnecessários em 'recount'
            $notes->each(function ($note) {
                if($note->recount) {
                    $note->recount->is_filial = true;
                    $note->recount->makeHidden(['users', 'notes']);
                }
            });

            // Retorno da resposta
            return count($notes) ? response()->json(['notes' => $notes], Response::HTTP_OK) : response()->json([], Response::HTTP_NOT_FOUND);

        } catch (Exception|ValidationException $e){
            return response()->json(['error' => ['message' => $e instanceof ValidationException ? $e->errors() : $e->getMessage(),]], Response::HTTP_BAD_REQUEST);
        }
    }

    public function create(Request $request): JsonResponse
    {
        try {
            $request->validate([
                'ids' => 'required|array|min:1|max:60|distinct|exists:filial_notes,id',
            ]);

            $user = auth()->guard('api')->user();

            $notesIds = $request->input('ids', []);

            (new FilialRecount())->withoutRelations()->create([
                'user_id' => $user->id,
                'status' => FilialRecount::STATUS_IN_PROGRESS,
            ]);

            $recount = FilialRecount::where('user_id', $user->id)->orderBy('id', 'desc')->first();

            $notes = FilialNote::whereIn('id', $notesIds)
                ->where('recount_id', null)
                ->update(['recount_id' => $recount->id]);

            event(new AtualizaNotaCegaEvent($recount->notes, FilialBlindNote::class, FilialBlindNote::STATUS_EM_CONFERENCIA));

            return response()->json(['message' => 'Conferencia criada com sucesso', 'recount_id' => $recount->id], Response::HTTP_CREATED);

        } catch (Exception|ValidationException $e){
            Log::info("FilialRecountController [create] - Erro ao realizar requisição : {$e->getMessage()}");
            return response()->json(['error' => ['message' => $e instanceof ValidationException ? $e->errors() : $e->getMessage(),]], Response::HTTP_BAD_REQUEST);
        }
    }

    public function addItem($id, Request $request): JsonResponse
    {
        $request->merge(['recount_id' => $id]);

        try {
            $request->validate([
                'recount_id'        => 'required|exists:filial_recounts,id',
                'cod_mat'           => 'required|numeric|min:0',
                'volumes'           => 'required|numeric',
                'quantity_confer'   => 'required|numeric',
                'quantity_damage'   => 'required|numeric',
            ]);

            $user = auth()->guard('api')->user();

            $recount = FilialRecount::findOrFail($request->input('recount_id', null));

            if ($recount->status != FilialRecount::STATUS_IN_PROGRESS){
                throw new Exception("Conferência não está em andamento");
            }

            $item = FilialRecountItems::create([
                'recount_id'      => $request->input('recount_id', null),
                'cod_mat'         => $request->input('cod_mat', null),
                'volumes'         => $request->input('volumes', 0),
                'quantity_confer' => $request->input('quantity_confer', 0),
                'quantity_damage' => $request->input('quantity_damage', 0),
                'user_id'         => $user->id
            ]);

            $recount->users()->syncWithoutDetaching([
                $user->id => ['recount_id' => $recount->id]
            ]);

            return response()->json(['message' => 'Item adicionado com sucesso', 'id' => $item->id], Response::HTTP_CREATED);
        } catch (Exception|ValidationException $e){
            Log::info("FilialRecountController [addItem] - Erro ao realizar requisição : {$e->getMessage()}");
            return response()->json(['error' => ['message' => $e instanceof ValidationException ? $e->errors() : $e->getMessage(),]], Response::HTTP_BAD_REQUEST);
        }
    }

    public function viewItems($id, Request $request): JsonResponse
    {
        try {
            $request->merge(['recount_id' => $id]);

            $request->validate([
                'recount_id' => 'required|integer|exists:filial_recounts,id',
            ]);

            $user = auth()->guard('api')->user();

            $recount = FilialRecount::with('products')->findOrFail($id);
            $sortedProducts = $recount->products->sortBy('description')->values();

            $formattedProducts = $sortedProducts->transform(function ($item) {
                return $item->getFormattedResponse();
            });

            return response()->json(['id' => $recount->id, 'products' => $formattedProducts,], Response::HTTP_OK);
        } catch (Exception|ValidationException $e){
            return response()->json(['error' => ['message' => $e instanceof ValidationException ? $e->errors() : $e->getMessage(),]], Response::HTTP_BAD_REQUEST);
        }
    }

    public function finalize($id, Request $request): JsonResponse
    {
        try {
            $request->merge(['recount_id' => $id]);

            $request->validate([
                'recount_id' => 'required|integer|exists:filial_recounts,id',
            ]);

            $user = auth()->guard('api')->user();

            $recount = FilialRecount::findOrFail($request->input('recount_id', null));

            if ($recount->status != FilialRecount::STATUS_IN_PROGRESS){
                throw new Exception("Conferência não está em andamento");
            }

            $recount->status = FilialRecount::STATUS_COMPLETED;
            $recount->save();

            $recount->users()->syncWithoutDetaching([
                $user->id => ['recount_id' => $recount->id]
            ]);

            event(new AtualizaNotaCegaEvent($recount->notes, FilialBlindNote::class, FilialBlindNote::STATUS_CONFERIDO));

            return response()->json(['message' => 'Conferência finalizada com sucesso!'], Response::HTTP_OK);
        } catch (Exception|ValidationException $e){
            Log::info("FilialRecountController [finalize] - Erro ao realizar requisição : {$e->getMessage()}");
            return response()->json(['error' => ['message' => $e instanceof ValidationException ? $e->errors() : $e->getMessage(),]], Response::HTTP_BAD_REQUEST);
        }
    }

}

app/Http/Controllers/FilialRecountController.php
<?php


namespace App\Http\Controllers;


use App\Entities\Filial\FilialBlindNote;
use App\Entities\Filial\FilialNote;
use App\Entities\Filial\FilialRecount;
use App\Events\AtualizaNotaCegaEvent;
use App\Helper\Helper;
use App\Jobs\ImportFilialBlindNotesJob;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpFoundation\Response;

class FilialRecountController
{
    public function index(Request $request): View|Factory|Application
    {
        $validated = $request->validate([
            'status' => ['nullable', 'string'],
            'q' => ['nullable', 'string']
        ]);

        $status = $validated['status'] ?? null;
        $search = $validated['q'] ?? null;

        $checksQuery = FilialRecount::with('entryReport')
            ->whereLike(['user.company_id'], auth()->user()->company_id)
            ->withCount('products')
            ->when($status, fn($query) => $query->where('status', $status))
            ->when($search, fn($query) => $query->search($search, ['id', 'status', 'user.name', 'notes.nfe', 'notes.name_provider']))
            ->orderBy('status', 'asc')
            ->orderByDesc('id');

        $checks = $checksQuery->paginate();

        return view('filial_recount.index', compact('checks'));
    }

    public function edit($id)
    {
        return FilialRecount::findOrFail($id);
    }

    public function import(): array
    {
        try {
            ImportFilialBlindNotesJob::dispatch()->onQueue('import');
            return Helper::getResponse('success', 'Importação assíncrona em andamento....', 'Recarregando em 2 segundos...', Response::HTTP_NO_CONTENT);
        } catch (Exception $ex) {
            return Helper::getResponse('error', 'Erro ao importar!', $ex->getMessage(), Response::HTTP_BAD_REQUEST);
        }
    }

    public function noteIndex(Request $request): View|Factory|Application
    {
        $validated = $request->validate([
            'status' => ['nullable', 'string'],
            'q' => ['nullable', 'string']
        ]);

        $status = $validated['status'] ?? null;
        $search = $validated['q'] ?? null;

        $notesQuery = FilialNote::with(['recount'])
            ->where('company_id', auth()->user()->company_id)
            ->withCount('items')
            ->when($status, function ($query, $status) {
                $query->where(function ($q) use ($status) {
                    $q->when($status === FilialRecount::STATUS_PENDING, function ($q) {
                        $q->whereNull('recount_id')
                            ->orWhereHas('recount', fn($subQ) => $subQ->where('status', FilialRecount::STATUS_PENDING));
                    }, function ($q) use ($status) {
                        $q->whereHas('recount', fn($subQ) => $subQ->where('status', $status));
                    });
                });
            })
            ->when($search, fn($query) => $query->search($search, ['nfe', 'name_provider', 'moviment_order']))
            ->orderByDesc('id');

        $notes = $notesQuery->paginate();

        return view('filial_note.index', compact('notes'));
    }

    public function noteItems($id)
    {
        $note = FilialNote::findOrFail($id);

        return $note->getItems();
    }

    public function noteDestroy($id): array
    {
        try {
            $note = FilialNote::findOrFail($id);

            DB::transaction(function () use ($note) {
                $note->items()->delete();
                $note->delete();

                $check = FilialRecount::find($note->recount_id);
                if ($check) {
                    $check->delete();
                }
            });
            return Helper::getResponse('success', 'Ação realizada com sucesso!', 'Recarregando em 2 segundos...', Response::HTTP_NO_CONTENT);
        } catch (Exception $exception) {
            return Helper::getResponse('error', 'Não é possível realizar ação!', $exception->getMessage(), Response::HTTP_BAD_REQUEST);
        }
    }

    public function destroy($id): array
    {
        $recount = FilialRecount::findOrFail($id);

        try {
            $recount->items->each(function ($item) {
                $item->delete();
            });

            $recount->notes->each(function ($note) {
                $note->recount_id = null;
                $note->save();
            });

            event(new AtualizaNotaCegaEvent($recount->notes, FilialBlindNote::class, FilialBlindNote::STATUS_NAO_CONFERIDO));

            if (isset($recount->entryReport)) $recount->entryReport->delete();

            DB::table('filial_recount_users')->where('recount_id', $recount->id)->delete();

            $recount->delete();

            return Helper::getResponse('success', 'Ação realizada com sucesso!', 'Recarregando em 2 segundos...', Response::HTTP_NO_CONTENT);
        } catch (Exception $exception) {
            return Helper::getResponse('error', 'Não é possível realizar ação!', $exception->getMessage(), Response::HTTP_BAD_REQUEST);
        }
    }


}

resources/views/filial_recount/index.blade.php
@php use App\Entities\Filial\FilialRecount; @endphp
@extends('layouts.app', [
    'namePage' => 'Controle de Conferências entre Filiais',
    'class' => 'sidebar-mini',
    'activePage' => 'recounts',
    'activeNav' => '',
    'searchRoute' => route('filial-recounts.index'),
])

@section('content')
    <div class="panel-header panel-header-md">
        <div class="header text-center">
            <h2 class="title">Conferências - Filiais</h2>
            <p class="category">Controle de Conferência</p>
        </div>
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-primary btn-round text-white" href="{{ route('filial-recounts.index') }}">
                            Todos
                        </a>
                        <a class="btn btn-primary btn-round text-white"
                           href="{{ route('filial-recounts.index', ['status' => FilialRecount::STATUS_PENDING]) }}">
                            Pendentes
                        </a>
                        <a class="btn btn-primary btn-round text-white"
                           href="{{ route('filial-recounts.index', ['status' => FilialRecount::STATUS_IN_PROGRESS]) }}">
                            Conferindo
                        </a>
                        <a class="btn btn-primary btn-round text-white"
                           href="{{ route('filial-recounts.index', ['status' => FilialRecount::STATUS_COMPLETED]) }}">
                            Concluído
                        </a>

                        <div class="col-12 mt-2">
                            @include('alerts.success')
                            @include('alerts.errors')
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <div class="table-responsive">
                            <table id="datatable" class="table" cellspacing="0" width="100%">
                                <thead class=" text-primary">
                                <tr class="text-center">
                                    <th><b>#</b></th>
                                    <th><b>Conferente</b></th>
                                    <th><b>Fornecedor</b></th>
                                    <th><b>Empresa</b></th>
                                    <th><b>Itens</b></th>
                                    <th><b>Criado</b></th>
                                    <th><b>Atualizado</b></th>
                                    <th><b>Status</b></th>
                                    <th class="disabled-sorting text-left"><b>{{ __('Ações') }}</b></th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($checks ?? [] as $recount)
                                    <tr class="text-center">
                                        <td style="font-size: small"><b>{{ $recount->id }}</b></td>
                                        <td style="max-width: 200px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: small">{{ $recount->usernames }}</td>
                                        <td style="max-width: 150px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: small">{{ $recount->provider_names ?? '' }}</td>
                                        <td style="font-size: xx-small">{{ $recount->user->company->fantasy_name ?? '' }}</td>
                                        <td style="font-size: xx-small">{{ $recount->products_count ?? '' }}</td>
                                        <td style="font-size: x-small">{{ $recount->created_at->format('d/m/Y H:i') ?? '' }}</td>
                                        <td style="font-size: x-small">{{ $recount->updated_at ? $recount->updated_at->format('d/m/Y H:i') : "" }}</td>
                                        <td style="font-size: x-small">
                                            @if($recount->status == FilialRecount::STATUS_PENDING)
                                                <span class="alert alert-danger">{{ $recount->status_label }}</span>
                                            @elseif($recount->status == FilialRecount::STATUS_IN_PROGRESS)
                                                <span class="alert alert-warning">{{ $recount->status_label }}</span>
                                            @else
                                                <span class="alert alert-success">{{ $recount->status_label }}</span>
                                            @endif
                                        </td>
                                        <td id="bread-actions" class="pull-left">
                                            @if($recount->status == FilialRecount::STATUS_COMPLETED)
                                                <form class="pull-left"
                                                      action="{{ route('pdf.generate', ['view' => 'filial_recount']) }}"
                                                      method="post" target="_blank">
                                                    @csrf()
                                                    @if($recount->products_count >= 100 )
                                                        <a title="Download"
                                                           class="btn btn-icon btn-sm btn-warning a-center download-big-pdf"
                                                           href="#"
                                                           data-server="{{ env('SERVER_URL' ?? '192.168.0.17').env('SERVER_IRL' ?? '/estoque') }}"
                                                           data-action="{{ route('pdf.download', ['view' => 'filial_recount']) }}"
                                                           data-redirect="{{ route('filial-recounts.index') }}"
                                                           data-filename="{{ 'filial_recount' }}"
                                                           data-values='{{ $recount->id }}'
                                                        >
                                                            {!! '🖨️' !!}
                                                        </a>
                                                    @else
                                                        <input id="data" name="data" type="hidden" value='{{ $recount->id }}'>

                                                        <button title="Gerar PDF" class="btn btn-icon btn-sm btn-warning"
                                                                type="submit">
                                                            {!! '🖨️' !!}
                                                        </button>
                                                    @endif
                                                    <span style="color: white; font-size: xx-small">.</span>
                                                </form>

                                                <!-- Botão para abrir o modal -->
                                                <a href="#" class="btn btn-dark btn-icon btn-sm a-center show-modal-info"
                                                   data-toggle="modal"
                                                   data-target="#infoModal"
                                                   data-identifier="{{ "# $recount->id" }}"
                                                   data-info="{{ "Nota(s) :\n $recount->nfes" }}"
                                                   data-title="Informações Extras da Conferência - (Filiais)">
                                                    {!! '🔍️' !!}
                                                </a>

                                                <a title="CSV" class="btn btn-success btn-icon btn-sm a-center download-csv"
                                                   href="#"
                                                   data-action="{{ route('csv.export-recount', ['type' => 'filial-recount', 'id' => $recount->id]) }}"
                                                   data-type="recount"
                                                >
                                                    {!! '📉' !!}
                                                </a>
                                                @if(is_null($recount->entryReport))
                                                    <a title="Transformar" class="btn btn-info btn-icon btn-sm a-center do-request"
                                                       href="#"
                                                       data-message="{{ "Transformar registro em relatório de entrada?" }}"
                                                       data-redirect="{{ route('filial-recounts.index') }}"
                                                       data-request-type="{{ "POST" }}"
                                                       data-action="{{ route('entry-reports.store', ['table' => 'filial_recounts', 'reference_id' => $recount->id]) }}"
                                                    >
                                                        {!! '🔁' !!}
                                                    </a>
                                                @endif
                                            @endif
                                            @if(auth()->user()->isAdmin())
                                                <button title="Delete"
                                                        class="btn btn-icon btn-sm btn-danger pull-center do-request"
                                                        href="#"
                                                        data-action="{{ route('filial-recounts.destroy', $recount->id) }}"
                                                        data-redirect="{{ route('filial-recounts.index') }}"
                                                >
                                                    <i class="now-ui-icons ui-1_simple-remove"></i>
                                                </button>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="9" align="center">Nenhum dado cadastrado até o momento</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>

                        {{ $checks->appends(request()->all())->links('pagination::bootstrap-4') }}
                    </div>
                    <!-- end content-->
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <!-- end row -->
    </div>

    <note-items></note-items>
    @include('pdf.iframe')

    @include('info.recount_notes')

@endsection