routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Queue;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/',  url('/home'));

Route::group(['middleware' => ['auth']], function () {
    // HOME ROUTE
    Route::get('/home', 'HomeController@index')->name('home');

    //SUPPLY ROUTE
    Route::get('/supply/status', 'SupplyController@status')->name('supply.status');
    Route::post('/supply/multi-list', 'SupplyController@multiList')->name('supply.multi');

    //PROFILE ROUTES
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    //USERS ROUTES
    Route::get('/users/separators', 'UserController@getSeparators')->name('users.separators');
    Route::post('/users/{id}/toggle-status', 'UserController@toggleStatus')->name('users.toggleStatus');

    //PDF ROUTES
    Route::post('/pdf/{view}/', 'PDFController@generate')->name('pdf.generate');
    Route::post('/pdf/download/{view}', 'PDFController@download')->name('pdf.download');

    //CSV ROUTES
    Route::get('/csv/{type}/{id}/export', 'CSVController@exportRecount')->name('csv.export-recount');
    Route::post('/csv/list/export', 'CSVController@exportList')->name('csv.export-list');

    //NOTES ROUTES
    Route::get('/notes/', 'RecountController@noteIndex')->name('notes.index');
    Route::get('/notes/import', 'RecountController@import')->name('notes.import');
    Route::get('/notes/{id}/items/', 'RecountController@noteItems')->name('notes.items');
    Route::delete('/notes/{id}/destroy/', 'RecountController@noteDestroy')->name('notes.destroy');

    //FILIAL NOTES ROUTES
    Route::get('/filial-notes/', 'FilialRecountController@noteIndex')->name('filial-notes.index');
    Route::get('/filial-notes/import', 'FilialRecountController@import')->name('filial-notes.import');
    Route::get('/filial-notes/{id}/items/', 'FilialRecountController@noteItems')->name('filial-notes.items');
    Route::delete('/filial-notes/{id}/destroy/', 'FilialRecountController@noteDestroy')->name('filial-notes.destroy');

    //ENTRY REPORT ROUTES
    Route::get('/entry-reports/{type}/index', 'EntryReportController@index')->name('entry-reports.index');
    Route::post('/entry-reports/{reference_id}/{table}/store', 'EntryReportController@store')->name('entry-reports.store');
    Route::delete('/entry-reports/{id}/destroy/', 'EntryReportController@destroy')->name('entry-reports.destroy');
    Route::delete('/entry-reports/{id}/rollback/', 'EntryReportController@rollback')->name('entry-reports.rollback');

    //AUDIT ROUTES
    Route::get('/audits', 'AuditController@index')->name('audits.index');

    // CRUD ROUTES
    Route::resources([
        'supply'            => 'SupplyController' ,
        'users'      		=> 'UserController',
        'recounts'          => 'RecountController',
        'filial-recounts'   => 'FilialRecountController'
    ]);

    //QUEUES ROUTES
    Route::get('/queue/updates', 'QueueController@checkForUpdates')->name('queue.updates');

});

app/Http/Controllers/PDFController.php
<?php


namespace App\Http\Controllers;


use App\Entities\EntryReport;
use App\Entities\Filial\FilialRecount;
use App\Entities\Recount;
use App\Entities\SupplyList;
use App\Helper\Helper;
use Barryvdh\DomPDF\Facade as PDF;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Symfony\Component\HttpFoundation\Response as ResponseAlias;

class PDFController extends Controller
{
    public function generate($view, Request $request): Response
    {
        $data = $this->fillData($view, $request);

        $view = str_replace("filial_", '', $view);
        $view = 'pdf.' . $view;
        $pdf = PDF::loadView($view, json_decode($data, true) ?? []);
        $pdf->setPaper('A4', 'landscape');
        return $pdf->stream();
    }

    public function download($view, Request $request): ?array
    {
        ini_set('memory_limit', '-1');
        set_time_limit(0);

        try {
            $data = $this->fillData($view, $request);
            $view = str_replace("filial_", '', $view);
            $view = 'pdf.' . $view;
            $filename = $request['filename'] ?? 'file';

            $pdf = PDF::loadView($view, json_decode($data, true) ?? []);
            $pdf->setPaper('A4', 'landscape');
            //$pdf->setOptions(['isHtml5ParserEnabled' => true]);

            // save the generated PDF to Browser
            file_put_contents("reports/{$filename}.pdf", $pdf->output());

            return Helper::getResponse('success', 'Arquivo gerado com sucesso !', 'Recarregando em 2 segundos...', ResponseAlias::HTTP_NO_CONTENT, 'file_url', asset("reports/{$filename}.pdf"));
        } catch (Exception $ex) {
            return Helper::getResponse('error', 'Não é possível realizar ação!', $ex->getMessage(), ResponseAlias::HTTP_BAD_REQUEST);
        }
    }

    private function fillData($view, $request)
    {
        switch ($view) {
            case 'recount':
                $recount = Recount::with(['notes' => function ($query) {
                    $query->withCount('items');
                }, 'user', 'users', 'products'])->withCount(['totalNoteItems as total_notes_items_count'])->findOrFail($request->input('data') ?? null);
                return json_encode($recount->toArray());

            case 'filial_recount':
                $recount = FilialRecount::with(['notes' => function ($query) {
                    $query->withCount('items');
                }, 'user', 'users', 'products'])->withCount(['totalNoteItems as total_notes_items_count'])->findOrFail($request->input('data') ?? null);
                return json_encode($recount->toArray());

            case 'supply_list_by_local':
                $list = SupplyList::with(['products', 'user', 'separator', 'products'])->findOrFail($request->input('data') ?? null);
                return json_encode($list->toArray());

            case 'entry_report':
                $entryReport = EntryReport::with([
                    'items' => function ($query) {
                        $query->with('product', 'separator', 'receiver');
                    },
                    'related' => function ($query) {
                        $query->without('users', 'notes');
                    },
                    'users',
                    ])
                    ->withCount('items')
                    ->findOrFail($request->input('data') ?? null);

                return json_encode($entryReport->toArray());

            default:
                return $request['data'];
        }
    }

    /* -----------------------CHAMADAS ESTATICAS -----------------------------*/
    public static function staticGenerate($view, $data): Response
    {
        $view = 'pdf.' . $view;
        $pdf = PDF::loadView($view, $data ?? []);

        return $pdf->stream();
    }

    public static function staticDownload($view, $filename, $data): ?array
    {
        ini_set('memory_limit', '-1');
        set_time_limit(0);

        $view = 'pdf.' . $view;

        try {
            $pdf = PDF::loadView($view, json_decode($data, true) ?? []);
            $pdf->setPaper('A4', 'landscape');
            //$pdf->setOptions(['isHtml5ParserEnabled' => true]);

            // save the generated PDF to Browser
            file_put_contents("reports/{$filename}.pdf", $pdf->output());

            return Helper::getResponse('success', 'Arquivo gerado com sucesso !', 'Recarregando em 2 segundos...', ResponseAlias::HTTP_NO_CONTENT, 'file_url', asset("reports/{$filename}.pdf"));
        } catch (Exception $ex) {
            return Helper::getResponse('error', 'Não é possível realizar ação!', $ex->getMessage(), ResponseAlias::HTTP_BAD_REQUEST);
        }
    }

}

resources/views/note/index.blade.php
@php use App\Entities\Recount; @endphp
@extends('layouts.app', [
    'namePage' => 'Notas para conferencia',
    'class' => 'sidebar-mini',
    'activePage' => 'recounts',
    'activeNav' => '',
    'searchRoute' => route('notes.index'),
])

@section('content')
    <div class="panel-header panel-header-md">
        <div class="header text-center">
            <h2 class="title">{{ "Notas de entrada - Fornecedor" }}</h2>
            <p class="category">Lista de itens cadastrados</p>
        </div>
    </div>
    <div class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-primary btn-round text-white" href="{{ route('notes.index') }}">
                            Todos
                        </a>
                        <a class="btn btn-primary btn-round text-white"
                           href="{{ route('notes.index', ['status' => Recount::STATUS_PENDING]) }}">
                            Pendentes
                        </a>
                        <a class="btn btn-primary btn-round text-white"
                           href="{{ route('notes.index', ['status' => Recount::STATUS_IN_PROGRESS]) }}">
                            Conferindo
                        </a>
                        <a class="btn btn-primary btn-round text-white"
                           href="{{ route('notes.index', ['status' => Recount::STATUS_COMPLETED]) }}">
                            Concluído
                        </a>

                        <a class="btn btn-primary btn-round text-white pull-right do-request"
                           href="#"
                           data-request-type="{{ "GET" }}"
                           data-message="{{ "Deseja importar notas de entrada?" }}"
                           data-action="{{ route('notes.import') }}"
                           data-redirect="{{ route('notes.index') }}"
                        >
                            {{ 'Importar' }}
                        </a>
                        <div class="col-12 mt-2">
                            @include('alerts.success')
                            @include('alerts.errors')
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="toolbar">
                            <!--        Here you can write extra buttons/actions for the toolbar              -->
                        </div>
                        <div class="table-responsive">
                            <table id="datatable" class="table">
                                <thead class="text-primary">
                                <tr class="text-center">
                                    <th><b>#</b></th>
                                    <th><b>NF-E</b></th>
                                    <th><b>Fornecedor</b></th>
                                    <th><b>Empresa</b></th>
                                    <th><b>Dt. Argos</b></th>
                                    <th><b>Atualizado</b></th>
                                    <th><b>Produtos</b></th>
                                    <th><b>Status</b></th>
                                    <th class="disabled-sorting text-left"><b>{{ __('Ações') }}</b></th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($notes ?? [] as $note)
                                    <tr class="text-center">
                                        <td><b>{{ $note->id }}</b></td>
                                        <td>{{ $note->nfe ?? '' }}</td>
                                        <td style="max-width: 150px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: small">
                                            {{ $note->name_provider ?? '' }}
                                        </td>
                                        <td style="font-size: xx-small">{{ $note->company->fantasy_name ?? '' }}</td>
                                        <td style="font-size: x-small">{{ $note->input_date->format('d/m/Y') ?? '' }}</td>
                                        <td style="font-size: x-small">{{ $note->updated_at ? $note->updated_at->format('d/m/Y H:i') : "" }}</td>
                                        <td style="font-size: x-small">{{ $note->items_count }}</td>
                                        <td style="font-size: x-small">
                                            @if($note->status == Recount::STATUS_PENDING)
                                                <span class="alert alert-danger">{{ $note->status_label }}</span>
                                            @elseif($note->status == Recount::STATUS_IN_PROGRESS)
                                                <span class="alert alert-warning">{{ $note->status_label }}</span>
                                            @else
                                                <span class="alert alert-success">{{ $note->status_label }}</span>
                                            @endif
                                        </td>
                                        <td id="bread-actions" class="pull-left">

                                            <button title="Produtos"
                                                    class="btn btn-info btn-icon btn-sm pull-center openModal"
                                                    data-toggle="modal"
                                                    data-target="#formModal"
                                                    data-title="{{ "Itens da NF-e: #$note->nfe" }}"
                                                    data-retrieve-items="{{ route('notes.items', $note->id) }}"
                                            >
                                                {!! '📦' !!}
                                            </button>

                                            @if(auth()->user()->isAdmin())
                                                <button title="Delete"
                                                        class="btn btn-icon btn-sm btn-danger pull-center do-request"
                                                        href="#"
                                                        data-message="{{ "Deseja confirmar exclusão ?" }}"
                                                        data-action="{{ route('notes.destroy', $note->id) }}"
                                                        data-redirect="{{ route('notes.index') }}"
                                                >
                                                    <i class="now-ui-icons ui-1_simple-remove"></i>
                                                </button>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr class="text-center">
                                        <td colspan="9">Nenhum dado cadastrado até o momento</td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                        {{ $notes->appends(request()->all())->links('pagination::bootstrap-4') }}
                    </div>
                    <!-- end content-->
                </div>
                <!--  end card  -->
            </div>
            <!-- end col-md-12 -->
        </div>
        <!-- end row -->
    </div>

    <note-items></note-items>

@endsection